-- ==============================================================================
-- SUPABASE MIGRATION: Dedicated Real-time Star Blessings Table
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/diwifzmzrouyzrqsyzgm/sql)
-- ==============================================================================

-- 1. Create table for global star blessings
CREATE TABLE IF NOT EXISTS public.star_blessings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.star_blessings ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read and insert permissions
CREATE POLICY "Allow public read on star_blessings" 
    ON public.star_blessings FOR SELECT 
    USING (true);

CREATE POLICY "Allow public insert on star_blessings" 
    ON public.star_blessings FOR INSERT 
    WITH CHECK (true);

-- 4. Enable Realtime Replication
ALTER PUBLICATION supabase_realtime ADD TABLE public.star_blessings;
